# Generated by Django 2.2.1 on 2020-02-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionoperation',
            name='msg_format',
            field=models.TextField(default=None, verbose_name='消息格式'),
        ),
    ]
