# Generated by Django 2.2.1 on 2020-02-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20200203_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionoperation',
            name='msg_format',
            field=models.TextField(default='Host(HOSTNAME:{hostname},IP:{ip}) \nSERVICE:{service_name}) has issue \nMSG:{msg},TIME:{time}', verbose_name='消息格式'),
        ),
    ]
